In [1]:
import requests
from bs4 import BeautifulSoup

r=requests.get("http://www.century21.com/real-estate/boston-ma/LCMABOSTON/")
c=r.content

soup=BeautifulSoup(c, "html.parser")

all_cards=soup.find_all("div", {"class": "property-card"})

In [62]:
l=[]

for item in all_cards:
    d={}
    
    price = item.find("a", {"class": "listing-price"}).text.replace("\n","").replace(" ","")
    d["Price"]=price
    
    
    address = item.find_all("div", {"class": "property-address"})[0].text.strip()
    d["Address"]=address
    
    city = item.find_all("div", {"class": "property-city"})[0].text.strip()
    d["City"]=city
    
    #Error handling in case there are no beds or baths
    try:
        bed = item.find("div", {"class": "property-beds"}).text.strip()
        d["Bed"]=bed
    except:
        d["Bed"]=None
        pass
    try:
        bath = item.find("div", {"class": "property-baths"}).text.strip()
        d["Bath"]=bath
    except:
        d["Bath"]=None
        pass
    
    l.append(d)

[{'Address': '14 Putnam St',
  'Bath': '3 baths',
  'Bed': '5 beds',
  'City': 'Boston MA 02129',
  'Price': '$1,825,000'},
 {'Address': '85 Saint Botolph St Unit 1',
  'Bath': '1 bath',
  'Bed': '2 beds',
  'City': 'Boston MA 02116',
  'Price': '$849,000'},
 {'Address': '38 Hardwick St',
  'Bath': '1 bath',
  'Bed': '3 beds',
  'City': 'Boston MA 02135',
  'Price': '$759,900'},
 {'Address': '477 Elm Street',
  'Bath': '2 baths',
  'Bed': '4 beds',
  'City': 'Braintree MA 02184',
  'Price': '$619,900'},
 {'Address': '45 West Third Street Unit 402-413',
  'Bath': '3 baths',
  'Bed': '3 beds',
  'City': 'Boston MA 02127',
  'Price': '$1,995,000'},
 {'Address': '555 Columbus Avenue Unit 1',
  'Bath': '1 bath',
  'Bed': '1 bed',
  'City': 'Boston MA 02118',
  'Price': '$519,900'},
 {'Address': '34 Edson St',
  'Bath': '1 bath',
  'Bed': '3 beds',
  'City': 'Boston MA 02124',
  'Price': '$369,900'},
 {'Address': '84 Geraldine Lane',
  'Bath': '2 baths',
  'Bed': '4 beds',
  'City': 'Braintree MA 02184',
  'Price': '$779,000'},
 {'Address': '84 Bunker Hill Street #3',
  'Bath': '1 bath',
  'Bed': '1 bed',
  'City': 'Charlestown MA 02129',
  'Price': '$475,000'},
 {'Address': '14 Leverett Avenue #1A',
  'Bath': '1 bath',
  'Bed': '2 beds',
  'City': 'East Bosotn MA 02128',
  'Price': '$314,900'},
 {'Address': '45 West Third Street Unit 508',
  'Bath': '2 baths',
  'Bed': '2 beds',
  'City': 'Boston MA 02127',
  'Price': '$1,175,000'},
 {'Address': '45 West Third Street Unit 329',
  'Bath': '2 baths',
  'Bed': '2 beds',
  'City': 'Boston MA 02127',
  'Price': '$1,025,000'},
 {'Address': '45 West Third Street Unit 514',
  'Bath': '1 bath',
  'Bed': '1 bed',
  'City': 'Boston MA 02127',
  'Price': '$930,000'},
 {'Address': '13 Mercer St 1',
  'Bath': '2 baths',
  'Bed': '3 beds',
  'City': 'Boston MA 02127',
  'Price': '$799,000'},
 {'Address': '143-171 Hyde Park Ave 169A',
  'Bath': '2 baths',
  'Bed': '3 beds',
  'City': 'Boston MA 02130',
  'Price': '$769,000'},
 {'Address': '27 Marcella St 5',
  'Bath': '2 baths',
  'Bed': '3 beds',
  'City': 'Boston MA 02119',
  'Price': '$649,000'},
 {'Address': '243 Belgrade Ave A',
  'Bath': '2 baths',
  'Bed': '4 beds',
  'City': 'Boston MA 02131',
  'Price': '$579,000'},
 {'Address': '6 Whittier Pl 16C',
  'Bath': '1 bath',
  'Bed': '1 bed',
  'City': 'Boston MA 02114',
  'Price': '$569,000'},
 {'Address': '125 Brayton Road',
  'Bath': '2 baths',
  'Bed': '3 beds',
  'City': 'Brighton MA 02135',
  'Price': '$624,900'},
 {'Address': '27 Mount Vernon Street Unit 2',
  'Bath': '2 baths',
  'Bed': '3 beds',
  'City': 'Boston MA 02129',
  'Price': '$1,169,000'}]

In [63]:
import pandas
df=pandas.DataFrame(l)

df

,Address,Bath,Bed,City,Price
0,14 Putnam St,3 baths,5 beds,Boston MA 02129,"$1,825,000"
1,85 Saint Botolph St Unit 1,1 bath,2 beds,Boston MA 02116,"$849,000"
2,38 Hardwick St,1 bath,3 beds,Boston MA 02135,"$759,900"
3,477 Elm Street,2 baths,4 beds,Braintree MA 02184,"$619,900"
4,45 West Third Street Unit 402-413,3 baths,3 beds,Boston MA 02127,"$1,995,000"
5,555 Columbus Avenue Unit 1,1 bath,1 bed,Boston MA 02118,"$519,900"
6,34 Edson St,1 bath,3 beds,Boston MA 02124,"$369,900"
7,84 Geraldine Lane,2 baths,4 beds,Braintree MA 02184,"$779,000"
8,84 Bunker Hill Street #3,1 bath,1 bed,Charlestown MA 02129,"$475,000"
9,14 Leverett Avenue #1A,1 bath,2 beds,East Bosotn MA 02128,"$314,900"
10,45 West Third Street Unit 508,2 baths,2 beds,Boston MA 02127,"$1,175,000"
11,45 West Third Street Unit 329,2 baths,2 beds,Boston MA 02127,"$1,025,000"
12,45 West Third Street Unit 514,1 bath,1 bed,Boston MA 02127,"$930,000"
13,13 Mercer St 1,2 baths,3 beds,Boston MA 02127,"$799,000"
14,143-171 Hyde Park Ave 169A,2 baths,3 beds,Boston MA 02130,"$769,000"
15,27 Marcella St 5,2 baths,3 beds,Boston MA 02119,"$649,000"
16,243 Belgrade Ave A,2 baths,4 beds,Boston MA 02131,"$579,000"
17,6 Whittier Pl 16C,1 bath,1 bed,Boston MA 02114,"$569,000"
18,125 Brayton Road,2 baths,3 beds,Brighton MA 02135,"$624,900"
19,27 Mount Vernon Street Unit 2,2 baths,3 beds,Boston MA 02129,"$1,169,000"

In [ ]:
df.to_csv("Output.")